### ISSUE TITLE
Le lien sur "Pour toute suggestion, vous pouvez nous" est incorrect

### ISSUE THREAD

**Issue by tporquet** [istex/istex-api-demo#5]
Ce lien point vers javascript:localStorage.clear(); plutôt que vers mailto.
D'ailleurs, ce lien sur "Pour toute suggestion, vous pouvez nous" pourrait être tout simplement supprimé puisque le mailto est déjà positionné sur "écrire ici".
![demoistex](https://cloud.githubusercontent.com/assets/2981650/22820248/35a6aa9e-ef76-11e6-945d-0da70f76135e.png)

**Comment by niederlec** [comment]
Oui, c'est un bug... une balise </a> manquante
Et c'est moi le coupable :cry: ...

**Comment by niederlec** [comment]
ça y est, c'est corrigé.

**Comment by tporquet** [comment]
Merci !
