### ISSUE TITLE
docker-compse up error

### ISSUE THREAD

**Issue by delanoe** [istex/istex-api-demo#9]
Hello,
running docker-compose up I get this error:

bower requirejs-html#~1.2.0            ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/DejaMi/requirejs-html.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/DejaMi/requirejs-html.git/'

Additional error details:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/DejaMi/requirejs-html.git/'

How to fix it please ? Thanks in advance

**Comment by niederlec** [comment]
Hello,
It looks that we use a deprecated library (requirejs-html github repository does not exists anymore).
It have pushed an bugfix attempt to the [bugfix-requirejs](https://github.com/istex/istex-api-demo/tree/bugfix-requirejs) branch. Could you try it ?

**Comment by delanoe** [comment]
Hello,
many thanks for this very quick fix that works perfectly.
And congratulations for this great project!
Regards,
